//// Generated by Protozoa from test.proto
//// 
//// This file is auto-generated and can be safely deleted and regenerated.
//// To regenerate all proto files, run: gleam run -m protozoa
//// 
//// DO NOT EDIT THIS FILE MANUALLY - all changes will be lost on regeneration.

import gleam/dict
import gleam/option.{None, Some}
import protozoa/decode
import protozoa/encode

pub type SimpleMessage {
  SimpleMessage(
    name: String,
    age: Int,
  )
}

pub type WithOneofValue {
  StrVal(String)
  IntVal(Int)
  BoolVal(Bool)
}

pub type WithOneof {
  WithOneof(
    value: option.Option(WithOneofValue),
  )
}

pub fn encode_withoneof(withoneof: WithOneof) -> BitArray {
  encode.message([
    case withoneof.value {
      Some(oneof_value) -> {
        case oneof_value {
      StrVal(value) -> encode.string_field(1, value)
      IntVal(value) -> encode.int32_field(2, value)
      BoolVal(value) -> encode.bool_field(3, value)
        }
      }
      None -> <<>>
    },
  ])
}

pub fn encode_simplemessage(simplemessage: SimpleMessage) -> BitArray {
  encode.message([
    encode.string_field(1, simplemessage.name),
    encode.int32_field(2, simplemessage.age),
  ])
}

fn oneof_value_decoder() -> decode.Decoder(option.Option(WithOneofValue)) {
  decode.from_field_dict(fn(fields) {
    case dict.get(fields, 1) {
      Ok([field, ..]) -> {
        case decode.string_field(field) {
          Ok(value) -> Ok(option.Some(StrVal(value)))
          Error(_) -> {
    case dict.get(fields, 2) {
      Ok([field, ..]) -> {
        case decode.int32_field(field) {
          Ok(value) -> Ok(option.Some(IntVal(value)))
          Error(_) -> {
    case dict.get(fields, 3) {
      Ok([field, ..]) -> {
        case decode.bool_field(field) {
          Ok(value) -> Ok(option.Some(BoolVal(value)))
          Error(_) -> Ok(option.None)
        }
      }
      _ -> Ok(option.None)
    }
          }
        }
      }
      _ -> {
    case dict.get(fields, 3) {
      Ok([field, ..]) -> {
        case decode.bool_field(field) {
          Ok(value) -> Ok(option.Some(BoolVal(value)))
          Error(_) -> Ok(option.None)
        }
      }
      _ -> Ok(option.None)
    }
      }
    }
          }
        }
      }
      _ -> {
    case dict.get(fields, 2) {
      Ok([field, ..]) -> {
        case decode.int32_field(field) {
          Ok(value) -> Ok(option.Some(IntVal(value)))
          Error(_) -> {
    case dict.get(fields, 3) {
      Ok([field, ..]) -> {
        case decode.bool_field(field) {
          Ok(value) -> Ok(option.Some(BoolVal(value)))
          Error(_) -> Ok(option.None)
        }
      }
      _ -> Ok(option.None)
    }
          }
        }
      }
      _ -> {
    case dict.get(fields, 3) {
      Ok([field, ..]) -> {
        case decode.bool_field(field) {
          Ok(value) -> Ok(option.Some(BoolVal(value)))
          Error(_) -> Ok(option.None)
        }
      }
      _ -> Ok(option.None)
    }
      }
    }
      }
    }
  })
}

pub fn withoneof_decoder() -> decode.Decoder(WithOneof) {
  use value <- decode.then(oneof_value_decoder())
  decode.success(WithOneof(value: value))
}

pub fn decode_withoneof(data: BitArray) -> Result(WithOneof, List(decode.DecodeError)) {
  decode.run(data, withoneof_decoder())
}

pub fn simplemessage_decoder() -> decode.Decoder(SimpleMessage) {
  use name <- decode.then(decode.string_with_default(1, ""))
  use age <- decode.then(decode.int32_with_default(2, 0))
  decode.success(SimpleMessage(name: name, age: age))
}

pub fn decode_simplemessage(data: BitArray) -> Result(SimpleMessage, List(decode.DecodeError)) {
  decode.run(data, simplemessage_decoder())
}